git:
  remote:
    upstream: 'mongodb/docs-atlas-cli'
    tools: 'mongodb/docs-tools'
project:
  name: 'atlas-cli'
  tag: 'atlas-cli'
  url: 'https://mongodb.com/docs/atlas/cli'
  title: "Atlas CLI"
  branched: true
system:
  tools:
    ref: HEAD
    pinned: false
  make:
    generated:
      - 'sphinx'
      - 'meta'
      - 'push'
      - 'integration'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
  files:
    - 'pdfs.yaml'
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'integration.yaml'
    - 'sphinx_local.yaml'
    - htaccess: ['htaccess.yaml']
version:
  release: '1.0.1'
  branch: 'master'
assets:
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
...
