name: mongodb
url: https://mongodb.com/docs/manual/
path: mongodb.inv
---
name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: python3
url: https://docs.python.org/3/
path: python3.inv
---
name: opsmanager
url: https://mongodb.com/docs/ops-manager/current/
path: objects.inv
...
